name: firebase_chat_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
#  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  firebase_auth: ^1.2.0
  firebase_database: ^8.1.0
  firebase_storage: ^10.2.5
#  sms_autofill: ^1.2.6
  sms_autofill: ^2.2.0
  shared_preferences: ^2.0.9
  intl: ^0.17.0
  get: ^4.3.8
  get_it: ^7.2.0
  image_picker: ^0.8.4+4
  file_picker: ^4.2.7
#  rive: ^0.7.33
  mvvm: ^0.1.9
  cloud_firestore: ^3.1.4
  status_view: ^0.0.1
  story_view: ^0.13.2
  permission_handler: ^8.3.0
  flutter_contact: ^0.9.1+8
  location_permissions: ^3.0.0
  location: ^4.3.0
  google_maps_flutter: ^2.1.1
  url_launcher: ^6.0.18
  flutter_background: ^1.1.0
  exif: ^3.1.1
  image: ^3.1.1
  flutter_sound_lite: ^8.5.0
  qr_flutter: ^4.0.0
  package_info_plus: ^1.3.0
  just_audio: ^0.9.19
  path_provider: ^2.0.8
  qr_code_scanner: ^0.6.1
  cached_network_image: ^3.2.0
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
#  image_downloader: ^0.31.0
  scan: ^1.6.0
  provider: ^6.0.2
#  localization_generator:
#    git: https://github.com/shana0440/localization_generator



dev_dependencies:
  flutter_test:
    sdk: flutter
#  agora_uikit: ^0.0.4
  agora_rtc_engine: ^5.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/country/
    - lib/Utils/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
